##Holt’s linear trend method

Holt (1957) extended simple exponential smoothing to allow forecasting of data with a trend. This method involves a forecast equation and two smoothing equations (one for the level and one for the trend):

$$\begin{aligned}
\text{Forecast equation}&& \pred{y}{t+h}{t} &= \ell_{t} + hb_{t} \\
\text{Level equation}&& \ell_{t} &= \alpha y_{t} + (1 - \alpha)(\ell_{t-1} + b_{t-1})\\
\text{Trend equation}&& b_{t} &= \beta^*(\ell_{t} - \ell_{t-1}) + (1 -\beta^*)b_{t-1}\end{aligned}$$

where $\ell_t$ denotes an estimate of the level of the series at time $t$, $b_t$ denotes an estimate of the trend (slope) of the series at time $t$, $\alpha$ is the smoothing parameter for the level, $0\le\alpha\le1$ and $\beta^*$ is the smoothing parameter for the trend, $0\le\beta^*\le1$ (we denote this as $\beta^*$ instead of $\beta$ for reasons that will be explained in Section \@ref(sec-7-ETS)).

As with simple exponential smoothing, the level equation here shows that $\ell_t$ is a weighted average of observation $y_t$ and the one-step-ahead training forecast for time $t$, here given by $\ell_{t-1} + b_{t-1}$. The trend equation shows that $b_t$ is a weighted average of the estimated trend at time $t$ based on $\ell_{t} - \ell_{t-1}$ and $b_{t-1}$, the previous estimate of the trend.

The forecast function is no longer flat but trending. The $h$-step-ahead forecast is equal to the last estimated level plus $h$ times the last estimated trend value. Hence the forecasts are a linear function of $h$.

[Air Passengers] In Table \@ref(tbl-7-Holts) we demonstrate the application
of Holt’s linear method to air transportation data for all passengers
with an Australian airline.

The smoothing paramters, $\alpha$ and $\beta$, and the initial values $\ell_0$ and $b_0$ are estimated by minimizing the SSE for the one-step training errors as in Section \@ref(sec-7-1-SES).

\@ref(tbl-7-Holts)=0.11cm

@rrc@

ccc@

cccc

&&& &\
**Year** & $t$ & $y_t$ & $\ell_t$ & $b_t$ & $\hat{y}_{t+1|t}$& $\ell_t$
& $b_t$ & $\hat{y}_{t+1|t}$\
1989 & 0 & & 15.71 & 1.73 & & 18.38 & 2.49 &\
1990 & 1 & 17.55 & 17.55 & 1.73 & 17.44 & 17.66 & 2.35 & 20.73\
1991 & 2 & 21.86 & 21.86 & 1.73 & 19.28 & 21.79 & 2.22 & 19.88\
1992 & 3 & 23.89 & 23.89 & 1.73 & 23.59 & 23.89 & 2.09 & 23.88\
1993 & 4 & 26.93 & 26.93 & 1.73 & 25.62 & 26.89 & 1.98 & 25.86\
1994 & 5 & 26.89 & 26.89 & 1.73 & 28.66 & 26.95 & 1.87 & 28.76\
1995 & 6 & 28.83 & 28.83 & 1.73 & 28.62 & 28.83 & 1.76 & 28.72\
1996 & 7 & 30.08 & 30.08 & 1.73 & 30.56 & 30.09 & 1.66 & 30.49\
1997 & 8 & 30.95 & 30.95 & 1.73 & 31.80 & 30.98 & 1.57 & 31.66\
1998 & 9 & 30.19 & 30.19 & 1.73 & 32.68 & 30.26 & 1.48 & 32.46\
1999 & 10 & 31.58 & 31.58 & 1.73 & 31.91 & 31.58 & 1.40 & 31.66\
2000 & 11 & 32.58 & 32.58 & 1.73 & 33.31 & 32.59 & 1.32 & 32.90\
2001 & 12 & 33.48 & 33.48 & 1.73 & 34.31 & 33.49 & 1.25 & 33.84\
2002 & 13 & 39.02 & 39.02 & 1.73 & 35.21 & 38.87 & 1.18 & 34.67\
2003 & 14 & 41.39 & 41.39 & 1.73 & 40.75 & 41.34 & 1.11 & 39.98\
2004 & 15 & 41.60 & 41.60 & 1.73 & 43.12 & 41.62 & 1.05 & 42.39\
& $h$ & & & & $\hat{y}_{T+h|T}$ & & & $\hat{y}_{T+h|T}$\
2005 & 1 & & & & 43.33 & & & 42.62\
2006 & 2 & & & & 45.05 & & & 43.55\
2007 & 3 & & & & 46.78 & & & 44.44\
2008 & 4 & & & & 48.51 & & & 45.27\
2009 & 5 & & & & 50.24 & & & 46.06\

air \<- window(ausair,start=1990,end=2004) fit \<- holt(air, h=5)

fit$model$state fitted(fit) fit[[“mean”]]

![Forecasting Air Passengers in Australia (thousands of passengers). For
all methods $\alpha=0.8$ and $\beta^*=0.2$, and for the additive damped
trend method $\phi=0.85$. ](fig_7_trend.pdf)

\@ref(fig-7-trend)

fit3 \<- holt(air, damped=TRUE, h=5) plot(fit2, type=“o”, ylab=“Air
passengers in Australia (millions)”, xlab=“Year”, fcol=“white”,
plot.conf=FALSE) lines(fitted(fit1), col=“blue”) lines(fitted(fit2),
col=“red”) lines(fitted(fit3), col=“green”) lines(fit1[[“mean”]],
col=“blue”, type=“o”) lines(fit2[[“mean”]], col=“red”, type=“o”)
lines(fit3[[“mean”]], col=“green”, type=“o”) legend(“topleft”, lty=1,
col=c(“black”,“blue”,“red”,“green”), c(“Data”,“Holt’s linear
trend”,“Additive damped trend”))

##Damped trend methods

The forecasts generated by Holt’s linear method display a constant trend (increasing or decreasing) indefinitely into the future.

Empirical evidence indicates that these methods tend to over-forecast, especially for longer forecast horizons. Motivated by this observation, Gardner and McKenzie (1985) introduced a parameter that “dampens” the trend to a flat line some time in the future. Methods that include a damped trend have proven to be very successful and are arguably the most popular individual methods when forecasts are required automatically for many series.

In conjunction with the smoothing parameters $\alpha$ and $\beta^*$ (with values between 0 and 1 as in Holt’s method), this method also includes a damping parameter $0<\phi<1$:

$$\begin{aligned}
\pred{y}{t+h}{t} &= \ell_{t} + (\phi+\phi^2 + \dots + \phi^{h})b_{t} \\
\ell_{t} &= \alpha y_{t} + (1 - \alpha)(\ell_{t-1} + \phi b_{t-1})\\
b_{t} &= \beta^*(\ell_{t} - \ell_{t-1}) + (1 -\beta^*)\phi b_{t-1}.\end{aligned}$$

If $\phi=1$ the method is identical to Holt’s linear method. For values between $0$ and $1$, $\phi$ dampens the trend so that it approaches a constant some time in the future. In fact the forecasts converge to $\ell_T+\phi b_T/(1-\phi)$ as $h\rightarrow\infty$ for any value $0<\phi<1$. The effect of this is that short-run forecasts are trended while long-run forecasts are constant.

### Example 7 {-}.2    Air Passengers (continued) {#example-7.2air-passengers-continued .unnumbered}

Figure \@ref(fig-7-trend) shows the one-step training forecasts, and the forecasts for years 2005--2010 generated from Holt’s linear trend method, and additive damped trend. The most optimistic forecasts come from the exponential trend method while the least optimistic come from the damped trend method, with the forecasts generated by Holt’s linear trend method somewhere between the two.

[Sheep in Asia]\@ref(ex-7-comp)

In this example we compare the forecasting performance of all the non-seasonal methods we have considered so far in forecasting the sheep livestock population in Asia. The data spans the period 1970--2007. We withhold the period 2001--2007 as a test set, and use the data up to and including year 2000 for the training set (see Section 2.5 for a definition of training and test sets). Figure \@ref(fig-7-comp) shows that data and the forecasts from all methods.

The parameters and initial values of the methods are estimated for all methods by minimizing SSE (as specified in Equation ) over the training set. In Table \@ref(tbl-7-comp) we present the estimation results and error measures over the training and the test sets.

livestock2 \<- window(livestock,start=1970,end=2000) fit1 \<-
ses(livestock2) fit2 \<- holt(livestock2) fit4 \<-
holt(livestock2,damped=TRUE) \# Results for first model: fit1[[“model”]]
accuracy(fit1) \# training set accuracy(fit1,livestock) \# test set

\@ref(tbl-7-comp)=0.11cm

<span>lrrrrr</span> & SES & Holt’s & Exponential & Additive &
Multiplicative\
& & linear & trend & damped & damped\
&\
$\alpha$ & 1.00 & 0.98 & 0.98 & 0.99 & 0.98\
$\beta^*$ & -- & 0 & 0 & 0 & 0\
$\phi$ & -- & -- & -- & 0.98 & 0.98\
& & & & &\
$\ell_0$ & 263.92 & 257.78 & 255.52 & 254.58 & 254.69\
$b_0$ & -- & 5.01 & 1.01 & 5.39 & 1.02\
&\
RMSE & 14.77 & 13.92 & 14.06 & 14.00 & 14.03\
SSE & 6761.47 & 6006.06 & 6128.46 & 6080.26 & 6100.11\
&\
MAE & 20.38 & 10.69 & 9.64 & 14.18 & 11.77\
RMSE & 25.46 & 11.88 & 12.50 & 15.78 & 12.62\
MAPE & 4.60 & 2.54 & 2.33 & 3.26 & 2.76\
MASE & 2.26 & 1.19 & 1.07 & 1.57 & 1.31\

$^\dag$ the parameter is restricted to $\phi\le0.98$. See text for more
details.

For the simple exponential smoothing method, the estimated smoothing parameter is $\alpha=1$. This is expected as the series is clearly trending over time and simple exponential smoothing requires the largest possible adjustment in each step to capture this trend.

![Level and slope components for Holt’s linear trend method and the
additive damped trend method.](fig_7_LevelTrend.pdf)

\@ref(fig-7-leveltrend)

plot(fit2$model$state) plot(fit4$model$state)

![Forecasting livestock, sheep in Asia: comparing forecasting
performance of non-seasonal methods. ](fig_7_comp.pdf)

\@ref(fig-7-comp)

plot(fit3, type=“o”, ylab=“Livestock, sheep in Asia (millions)”, flwd=1,
plot.conf=FALSE) lines(window(livestock,start=2001),type=“o”)
lines(fit1$mean,col=2)
lines(fit2$mean,col=3) lines(fit4$mean,col=5)
lines(fit5$mean,col=6) legend(“topleft”, lty=1, pch=1, col=1:6,
c(“Data”,“SES”,“Holt’s”,“Damped trend”))

For the other methods, there is also a trend component.The smoothing parameter for the slope parameter is estimated to be zero, indicating that the trend is not changing over time. Of course, the trend estimated using the damped trend methods will change in the future due to the damping.

In Figure \@ref(fig-7-leveltrend), we plot the level and trend components for Holt’s method and for the damped trend method. The slope of the trend component for Holt’s method is constant, showing that the trend is linear. In contrast, the slope of the trend component for the damped trend method is decreasing, showing that the trend is levelling off.

For the damped trend method, the damping parameter $\phi$ is restricted to a maximum of 0.98 (the estimation returned an optimal value of $\phi=1$). This restriction is imposed to ensure that the damped trend method generates noticeably different forecasts from Holt’s linear method, otherwise we get identical forecasts.

The SSE measures calculated over the training set show that Holt’s linear trend method provides the best fit to the data followed by the additive damped trend method. Simple exponential smoothing generates the largest one-step training errors. In Figure \@ref(fig-7-comp) we can examine the forecasts generated by the methods. Pretending that we have not seen the data over the test-set we would conclude that all forecasts are quite plausible especially from the methods that account for the trend in the data.

Comparing the forecasting performance of the methods over the test set in Table \@ref(tbl-7-comp), ??? is the most accurate method according to the MAE, MAPE and MASE, while Holt’s linear method is most accurate according to the RMSE.

Conflicting results like this are very common when performing forecasting competitions between methods. As forecasting tasks can vary by many dimensions (length of forecast horizon, size of test set, forecast error measures, frequency of data, etc.), it is unlikely that one method will be better than all others for all forecasting scenarios. What we require from a forecasting method are consistently sensible forecasts, and these should be frequently evaluated against the task at hand.

