---
title: "Time series cross-validation figures"
author: "Rob J Hyndman"
output:
  beamer_presentation:
    fig_height: 3
    fig_width: 6
    keep_tex: no
    theme: "metropolis"
    includes:
      in_header: preamble.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## TSCV 1

```{r cv1, cache=TRUE, echo=FALSE, fig.height=4}
par(mar=c(0,0,0,0))
plot(0,0,xlim=c(0,28),ylim=c(0,1),
       xaxt="n",yaxt="n",bty="n",xlab="",ylab="",type="n")
h <- 1
for(j in 1:10)
{
  test <- (16+j):26
  train <- 1:(15+j)
  arrows(0,1-j/20,27,1-j/20,0.05)
  points(train,rep(1-j/20,length(train)),pch=19,col="blue")
  if(length(test) >= h)
    points(test[-h], rep(1-j/20,length(test)-1), pch=19, col="white")
  else
    points(test, rep(1-j/20,length(test)), pch=19, col="white")
  if(length(test) >= h)
    points(test[h], h-j/20, pch=19, col="red")
}
text(28,.95,"time")
```

## TSCV 2

```{r cv2, cache=TRUE, echo=FALSE, fig.height=4}
par(mar=c(0,0,0,0))
plot(0,0,xlim=c(0,28),ylim=c(0,1),
       xaxt="n",yaxt="n",bty="n",xlab="",ylab="",type="n")
h <- 2
for(j in 1:10)
{
  test <- (16+j):26
  train <- 1:(15+j)
  arrows(0,1-j/20,27,1-j/20,0.05)
  points(train,rep(1-j/20,length(train)),pch=19,col="blue")
  if(length(test) >= h)
    points(test[-h], rep(1-j/20,length(test)-1), pch=19, col="white")
  else
    points(test, rep(1-j/20,length(test)), pch=19, col="white")
  if(length(test) >= h)
    points(test[h], 1-j/20, pch=19, col="red")
}
text(28,.95,"time")
```

## TSCV 3

```{r cv3, cache=TRUE, echo=FALSE, fig.height=4}
par(mar=c(0,0,0,0))
plot(0,0,xlim=c(0,28),ylim=c(0,1),
       xaxt="n",yaxt="n",bty="n",xlab="",ylab="",type="n")
h <- 3
for(j in 1:10)
{
  test <- (16+j):26
  train <- 1:(15+j)
  arrows(0,1-j/20,27,1-j/20,0.05)
  points(train,rep(1-j/20,length(train)),pch=19,col="blue")
  if(length(test) >= h)
    points(test[-h], rep(1-j/20,length(test)-1), pch=19, col="white")
  else
    points(test, rep(1-j/20,length(test)), pch=19, col="white")
  if(length(test) >= h)
    points(test[h], 1-j/20, pch=19, col="red")
}
text(28,.95,"time")
```
